[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[general]
live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#ebdbb2"
text = "0x000000"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.vi_mode_cursor]
cursor = "#ebdbb2"
text = "0x000000"

[cursor]
blink_interval = 400
vi_mode_style = "Beam"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = false

[scrolling]
history = 5000

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
title = "alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 0

[keyboard]
