-- add more treesitter parsers
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    -- add tsx and treesitter
    vim.list_extend(opts.ensure_installed, {
      "bash",
      "csv",
      "dockerfile",
      "gitignore",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "rust",
      "jq",
      "just",
      "make",
      "proto",
      "sql",
      "svelte",
      "terraform",
      "tsx",
      "typescript",
      "toml",
      "vim",
      "yaml",
    })
  end,
}
